version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:20.18.0
    working_directory: ~/repo

jobs:
  install_dependencies:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-cache-{{ checksum "package-lock.json" }}  # Cache key based on package-lock
            - v1-npm-cache-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: v1-npm-cache-{{ checksum "package-lock.json" }}  # Cache node_modules folder

  test:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  build:
    jobs:
      - install_dependencies
      - test:
          requires:
            - install_dependencies
